FROM python:3.12.3-slim

LABEL maintainer="MFT Project"
LABEL description="API services for MFT Project"

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1

# Use the Yandex Mirror for Debian
RUN sed -i 's/deb.debian.org/mirror.yandex.ru/g' /etc/apt/sources.list.d/debian.sources && \
    sed -i 's/security.debian.org/mirror.yandex.ru\/debian-security/g' /etc/apt/sources.list.d/debian.sources

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./dockerfiles/requirements_api.txt .
RUN pip install --upgrade pip setuptools wheel && \
    pip install --no-cache-dir --only-binary :all: -r requirements_api.txt

COPY endpoints/ /app/endpoints/
COPY database/ /app/database/
COPY config/ /app/config/
COPY dags/ /app/dags/

ARG APP_UID=50000
ARG APP_GID=0

# If GID=0, use the existing root group
RUN if [ "${APP_GID}" = "0" ]; then \
        groupname="root"; \
    else \
        groupadd -g ${APP_GID} -r appgroup && groupname="appgroup"; \
    fi && \
    useradd -m -u ${APP_UID} -g ${groupname} -s /bin/bash appuser && \
    chown -R appuser:${groupname} /app && \
    mkdir -p /opt/airflow/data/{uploads,backups,processed,quarantine} && \
    chown -R appuser:${groupname} /opt/airflow/data

USER appuser

CMD ["python", "-m", "endpoints.mft_upload_api"]